import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.css';
import { CounterStoreProvider } from '@/app/store/providers/sample-store-provider';
import { MockProvider } from '@/app/MswProvider';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function CommonLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <header className="pl-4 pt-4">
        <Link href={'/'}>
          <Image width={60} height={60} src={'/images/logo.png'} alt="logo" />
        </Link>
      </header>
      <div className={inter.className}>{children}</div>
      <footer>
        <Link href={'/'}>copyright@를 빙자한 홈으로 가기 버튼</Link>
      </footer>
    </div>
  );
}
