import type { Metadata } from 'next';
import '@/app/globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import BottomNav from '@/components/layout/BottomNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function CommonLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="min-h-screen lg:flex">
        <Header />
        <div className="z-2 flex-1">
          {children}
          <Footer />
        </div>
      </div>
      <BottomNav />
    </>
  );
}
